/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_dashboard (void);
GtkWidget* create_mod (void);
GtkWidget* create_af (void);
GtkWidget* create_aj (void);
GtkWidget* create_def (void);
GtkWidget* create_fontselectiondialog1 (void);
